[COMPILE]
compiler = gcc
preprocessor = gcc -nostdinc -E -I ./vcInclude
#input file format
#- P : Preprocess file
#- S : Source file
input_file_format=S
proprecessor=gcc -E

[LANGUAGE]
language=CPP

[KEYWORD]
# Paths resolved relative to this config file's directory
cpp_keyword_path=../keywords/cpp_keyword.tbl
c_keyword_path=../keywords/c_keyword.tbl

[OUTPUT]
sequence_path=SEQUENCE.DNA
